# Uncomment this line to define a global platform for your project
# platform :ios, ‘6.0’
source 'https://github.com/CocoaPods/Specs.git'

target 'SmartHome' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'DZNEmptyDataSet'
pod 'JSONKit-NoWarning'
pod 'MJRefresh'
pod 'CocoaAsyncSocket'
pod 'GDataXML-HTML'
pod 'MagicalRecord'
end

